steps:
- name: 'docker/compose:1.29.2' # Or a newer version if available and desired
  entrypoint: 'docker-compose' # Specify the entrypoint for the builder
  env: ['DOCKER_BUILDKIT=1'] # Explicitly enable BuildKit
  args:
    - '-f' # Specify the compose file
    - 'docker-compose.buildkit.yml'
    - 'build' # The build command for docker-compose
    - 'n8n-mcp' # Specify the service to build from your compose file
images:
- 'gcr.io/$PROJECT_ID/n8n-mcp:latest' # Tag your image for Artifact Registry/Container Registry
